#
# Configuration
#

---

# (Workers, clients) Job servers ("host:port"; default port is 4730)
servers:
    - "127.0.0.1:4730"

# (Workers) Where should the worker put the logs (default is /var/log/gjs)
# worker_log_dir: "/var/log/gjs"

# (Workers) Notification emails
notification_emails:

    # Email address to send the email from (default is "gjs_donotreply@example.com")
    from_email: "gjs_donotreply@example.com"

    # Email subject prefix (default is "[GJS]")
    subject_prefix: "[GJS]"

    # Who should be notified about failed jobs (default is empty list)
    recipients:
        - "lvaliukas@cyber.law.harvard.edu"
